server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
  #eureka server 是有界面的，启动工程,打开浏览器访问： http://localhost:8761 ,界面如下：
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
